# Generated by Django 6.0.5 on 2026-05-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.IntegerField(default=300)),
                ('charge_points', models.IntegerField(default=500)),
                ('now_building', models.IntegerField(default=120)),
            ],
            options={
                'verbose_name': 'Network Statistic',
                'verbose_name_plural': 'Network Statistics',
            },
        ),
    ]
