# Generated by Django 6.0.5 on 2026-05-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_networkstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCoreTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(help_text='e.g., Vision, Mission, Values', max_length=50, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
