# Generated by Django 6.0.5 on 2026-05-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homeaboutimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAboutImage',
        ),
    ]
