# Generated by Django 6.0.5 on 2026-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_homeaboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(blank=True, help_text='e.g. 5 min read', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, help_text='e.g. TECHNOLOGY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, help_text='e.g. 10 Am To 10 Pm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='platform',
            field=models.CharField(default='YouTube', max_length=50),
        ),
    ]
