# Generated by Django 6.0.5 on 2026-05-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_blogcategory_blogtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='content.blogcategory'),
        ),
    ]
