# Generated by Django 6.0.5 on 2026-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='articles/')),
                ('category', models.CharField(blank=True, help_text='e.g. Charging Hubs', max_length=100, null=True)),
                ('author', models.CharField(default='Relux Team', max_length=100)),
                ('read_time', models.CharField(blank=True, help_text='e.g. 5 min read', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
