# Generated by Django 6.0.5 on 2026-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, help_text='e.g. YouTube or Instagram Video Link', null=True),
        ),
    ]
