# Generated by Django 6.0.5 on 2026-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_article_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='video_url',
        ),
        migrations.AddField(
            model_name='article',
            name='media_link',
            field=models.URLField(blank=True, help_text='e.g. https://timesofindia.indiatimes.com/...', null=True),
        ),
    ]
