# Generated by Django 6.0.5 on 2026-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_article_video_url_article_media_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. FUTURE IS', max_length=255)),
                ('highlight_text', models.CharField(help_text='e.g. NOW.', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Innovation', max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, help_text='e.g. 2 Years ago', max_length=100, null=True)),
                ('views_count', models.CharField(default='12K Views', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
