# Generated by Django 6.0.5 on 2026-05-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinquiry',
            name='franchise_model',
            field=models.CharField(blank=True, help_text='e.g., MINI 30KW, STD 60 KW', max_length=100, null=True),
        ),
    ]
