# Generated by Django 6.0.5 on 2026-05-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_franchiseinquiry_franchise_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinquiry',
            name='business_profile',
            field=models.CharField(blank=True, help_text='e.g., ENTREPRENEUR, REAL ESTATE OWNER', max_length=100, null=True),
        ),
    ]
