# Generated by Django 6.0.5 on 2026-05-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_franchiseinquiry_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='electricity_connection',
            field=models.CharField(blank=True, help_text='e.g., YES, NO', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='land_photo',
            field=models.FileField(blank=True, null=True, upload_to='zero_land_photos/'),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='land_size',
            field=models.CharField(blank=True, help_text='e.g., 2400', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='land_unit',
            field=models.CharField(blank=True, help_text='e.g., SQ.FT, ACRES', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zeroinvestmentpartner',
            name='location_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zeroinvestmentpartner',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
