# Generated by Django 6.0.5 on 2026-05-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_contactmessage_city_contactmessage_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='charger_connector',
            field=models.CharField(blank=True, help_text='e.g. CCS2, AC Type 2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='charger_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='location',
            name='charger_power',
            field=models.CharField(blank=True, help_text='e.g. 120 kW, 60 kW', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='facilities',
            field=models.TextField(blank=True, help_text='Comma-separated list, e.g. Restroom, Cafe, Seating Area', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='google_map_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
