# Generated by Django 6.0 on 2026-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_location_image_locationreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='franchiseinquiry',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='franchiseinquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseinquiry',
            name='response_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='response_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeroinvestmentpartner',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded')], default='new', max_length=20),
        ),
    ]
